# Generated by Django 4.1.13 on 2024-12-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_galleryindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsetting',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='email_sender',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='email_use_tls',
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='captcha',
            field=models.CharField(blank=True, help_text='Your captcha site key', max_length=255, verbose_name='Captcha key'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='content_margin_top',
            field=models.IntegerField(default=0, help_text='Margin top for content, use with fixed navbar settings', verbose_name='Content margin top (px)'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='Your Facebook page ID', max_length=255, verbose_name='Facebook page ID'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='footer_bg_color',
            field=models.CharField(blank=True, help_text='Footer background color value', max_length=500, null=True, verbose_name='Footer background color'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='language_menu',
            field=models.BooleanField(default=True, help_text='Show/hide language menu item', verbose_name='Language menu item'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='owner_mail',
            field=models.EmailField(help_text='Enter the email address of the account owner or administrator.', max_length=254, null=True, verbose_name='Owner mail'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='using_messenger',
            field=models.BooleanField(default=True, help_text='Show/hide Facebook Messenger chat support', verbose_name='Using Facebook Messenger chat support'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='using_whatsapp',
            field=models.BooleanField(default=True, help_text='Show/hide whatsapp chat support', verbose_name='Using whatsapp chat support'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='whatsapp_id',
            field=models.CharField(blank=True, help_text='Your Whatsapp ID', max_length=255, verbose_name='Whatsapp ID'),
        ),
    ]
