# Generated by Django 4.1.13 on 2025-01-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_remove_customsetting_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsetting',
            name='captcha',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='owner_mail',
        ),
        migrations.AddField(
            model_name='customsetting',
            name='captcha_secret_key',
            field=models.CharField(blank=True, help_text='Your reCAPTCHA v2 secret key', max_length=255, verbose_name='reCAPTCHA secret key'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='captcha_site_key',
            field=models.CharField(blank=True, help_text='Your reCAPTCHA v2 site key', max_length=255, verbose_name='reCAPTCHA site key'),
        ),
    ]
