# Generated by Django 4.1.13 on 2025-01-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_customsetting_captcha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='email_host',
            field=models.CharField(blank=True, help_text='Your Email Host', max_length=255, verbose_name='EMAIL_HOST'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Your Email Host Password', max_length=255, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Your Email Host User', max_length=255, verbose_name='EMAIL_HOST_USER'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='email_port',
            field=models.PositiveIntegerField(default=0, help_text='Your Email Port', verbose_name='EMAIL_PORT'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='email_sender',
            field=models.EmailField(help_text='Your email sender', max_length=254, null=True, verbose_name='Email Sender'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL', verbose_name='EMAIL_USE_SSL'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS', verbose_name='EMAIL_USE_TLS'),
        ),
    ]
