# Generated by Django 4.1.13 on 2025-01-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_customsetting_email_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsetting',
            name='email_host',
            field=models.CharField(blank=True, help_text='Your Email Host', max_length=255, verbose_name='Email host'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Email Host Password', max_length=255, verbose_name='Email host password'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Email Host User', max_length=255, verbose_name='Email host user'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='email_port',
            field=models.PositiveIntegerField(default=465, help_text='Your Email Port', verbose_name='Email port'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='email_sender',
            field=models.CharField(blank=True, help_text='The default email address this site appears to send from. For example: "sender@example.com" or "Sender Name <sender@example.com>" (without quotes)', max_length=255, null=True, verbose_name='From email address'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='email_use_ssl',
            field=models.BooleanField(default=True, help_text='Use SSL', verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='email_use_tls',
            field=models.BooleanField(default=False, help_text='Use TLS', verbose_name='Use TLS'),
        ),
    ]
